version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - broker

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: resource_hub
      MYSQL_USER: aaman007
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .db:/var/lib/mysql
    ports:
      - "33067:3306"

  broker:
    image: redis
    restart: always
    ports:
      - "63790:6379"
